name: build analyse, scan
on:
  push:
    branches:
      - main

jobs:
  build-analyse-scan:
    name: build
    runs-on: [self-hosted]
    steps:
      - name: checout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name:  Building code and analyse with sonarqube
        uses:  actions/checkout@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: dependencies_install
        run: npm install
      - name: trivy scan
        run: trivy fs . > trivyreport.txt
      - name: docker build push
        run: |
          docker build -t zomato .
          docker tag zomato anish0506/zomato.latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2 # This step logs in to the Docker Hub using the secrets
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build push images
        run: |    
          docker push anish0506/zomato.latest
      - name: trivy scan image
        run: trivy image anish0506/zomato.latest
  deploy: 
    needs: build-analyse-scan
    runs-on: [self-hosted]
    steps:
      - name: docker pull
        run: docker pull anish0506/zomato.latest
      - name: Image scan
        run: trivy image anish0506/zomato.latest
      - name: run docker container
        run: sudo docker run -itd -p 3000:3000 --name  anish0506/zomato.latest
